title: Train the Trainers - Crick Partnership & DAIM 2025
description: Train the Trainers workshop in bioimage analysis - Crick Partnership & DAIM 2025
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
